### ISSUE TITLE
Installation failed, use of unstable library feature.

### ISSUE THREAD

**Issue by mystique09** [sloganking/codevis#26]
Do I need to switch to rust nightly version to install codevis?

[ERROR]
```
error[E0658]: use of unstable library feature 'scoped_threads'
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/codevis-0.3.1/src/render.rs:338:13
    |
338 |             std::thread::scope(|scope| -> anyhow::Result<()> {
    |             ^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #93203 <https://github.com/rust-lang/rust/issues/93203> for more information

error[E0658]: use of unstable library feature 'scoped_threads'
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/codevis-0.3.1/src/render.rs:342:27
    |
342 |                     scope.spawn({
    |                           ^^^^^
    |
    = note: see issue #93203 <https://github.com/rust-lang/rust/issues/93203> for more information

For more information about this error, try `rustc --explain E0658`.
```

I use termux.
- Linux localhost 4.14.186-gfbf7287bd5c9-dirty
- aarch64 @
- Android

**Comment by sloganking** [comment]
You don’t need nightly. Scoped threads were a recent compiler addition. Make sure your rustc version is updated to at least 1.63.0

https://betterprogramming.pub/scoped-threads-the-great-addition-of-rust-1-63-0-2a4c1d411c0a?gi=f391e97778fc

**Comment by mystique09** [comment]
> You don’t need nightly. Scoped threads were a recent compiler addition. Make sure your `rustc` version is updated to at least `v1.63.0`
> 
> https://betterprogramming.pub/scoped-threads-the-great-addition-of-rust-1-63-0-2a4c1d411c0a?gi=f391e97778fc

Hmm weird, in termux the current stable version of rust is 1.62.1, maybe I'll just wait for the latest version. Thanks.

**Comment by sloganking** [comment]
You might also be able to uninstall the ‘rust’ package, install the ‘rustup’ package, and run ‘rustup update’

https://rust-lang.github.io/rustup/basics.html

**Comment by mystique09** [comment]
> You might also be able to uninstall the ‘rust’ package, install the ‘rustup’ package, and run ‘rustup update’
> 
> https://rust-lang.github.io/rustup/basics.html

I use termux, and rustup is not available in termux.
